/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'admin' at '07/02/15 19:40' with Gradle 2.2.1
 *
 * @author admin, @date 07/02/15 19:40
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
